### ISSUE TITLE
膜 #01 Worthless

### ISSUE THREAD

**Issue by xnth97** [MengXiangxi/xixi-bot#1]
The author of this repository is too brilliant that he should contribute to the humanity instead of wasting time on this kind of projects.

**Comment by MengXiangxi** [comment]
唉？TJUThesis怎么在你这里？？？

**Comment by xnth97** [comment]
我当年魔改了一下

**Comment by MengXiangxi** [comment]
你太强了.gif
你居然unstar了我……伤心。

**Comment by xnth97** [comment]
看了一下发现太没用了...
对院士浪费时间拖延科研进度的行为表示谴责

**Comment by MengXiangxi** [comment]
正在迭代升级！你不知道昨晚趁我睡觉时有多少人在调戏我！

**Comment by xnth97** [comment]
> 你不知道昨晚趁我睡觉时有多少人在调戏我！

这句话听起来好咸湿...

**Comment by MengXiangxi** [comment]
调戏我的bot！

**Comment by xnth97** [comment]
求调戏你

**Comment by MengXiangxi** [comment]
自己部署！
可以我们在两个微信号上各部署一个，然后放到同一个群里……

**Comment by xnth97** [comment]
太坏了...
不调戏bot，只调戏你（滑稽

**Comment by MengXiangxi** [comment]
如果我的bot能通过图灵测试，你就无法分辨在调戏谁。

**Comment by xnth97** [comment]
想用只会回复囍的bot通过图灵测试？稍有常识的人都会知道，你这螳臂当车的**

**Comment by MengXiangxi** [comment]
1. 你看代码了吗？至少有六种回复了现在。
2. 如果我作为自然人也只回复囍，那么观测者就无法区分我和bot了。
